const $$=(s)=>[...document.querySelectorAll(s)],$=(s)=>document.querySelector(s);
const views=$$('.view'),controls=$$('[data-route]'),sidebar=$('#sidebar'),backdrop=$('#backdrop'),menu=$('#menuToggle'),orbs=$$('.orb'),bossState=$('#bossState'),workLabel=$('#workLabel'),workDetail=$('#workDetail');
const routeStates={inicio:[['davinci','papagaio'],'coordenando','Coruja coordenando','Da Vinci e Papagaio apresentam o projeto.'],metodologia:[['macaco','galinha'],'orquestrando método','Método em foco','Macaco estrutura; Galinha testa o fluxo.'],pets:[['papagaio'],'apresentando equipe','Equipe PET ativa','Papagaio traduz as funções da equipe.'],evidencias:[['sherlock','galinha'],'validando','Evidência sob revisão','Sherlock rastreia; Galinha tenta refutar.'],biblioteca:[['sherlock','macaco'],'organizando fontes','Biblioteca em foco','Sherlock localiza; Macaco organiza.'],laboratorio:[['macaco'],'coordenando execução','Laboratório local','Macaco processa o arquivo no navegador.']};
function setState(pets=[],boss='coordenando',label='Coruja coordenando',detail='A equipe entra conforme a tarefa.'){const on=new Set(pets);orbs.forEach(x=>{x.classList.toggle('active',on.has(x.dataset.pet));x.setAttribute('aria-pressed',on.has(x.dataset.pet))});bossState.textContent=boss;workLabel.textContent=label;workDetail.textContent=detail}
function route(){return(location.hash||'#inicio').slice(1)||'inicio'}function apply(){setState(...(routeStates[route()]||routeStates.inicio))}
function go(name,push=true){const target=$('#view-'+name)||$('#view-inicio'),resolved=target.id.replace('view-','');views.forEach(x=>x.classList.toggle('active',x===target));controls.filter(x=>x.dataset.route).forEach(x=>x.classList.toggle('active',x.dataset.route===resolved));if(push&&location.hash!=='#'+resolved)history.pushState(null,'','#'+resolved);document.title=target.dataset.title+' — PET / CEPV';sidebar.classList.remove('open');backdrop.classList.remove('show');menu?.setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'smooth'});apply()}
controls.forEach(x=>x.addEventListener('click',e=>{e.preventDefault();go(x.dataset.route)}));addEventListener('hashchange',()=>go(route(),false));go(route(),false);
menu?.addEventListener('click',()=>{const open=sidebar.classList.toggle('open');backdrop.classList.toggle('show',open);menu.setAttribute('aria-expanded',open)});backdrop?.addEventListener('click',()=>{sidebar.classList.remove('open');backdrop.classList.remove('show');menu?.setAttribute('aria-expanded','false')});
const info={macaco:['Macaco executando','Código, estrutura e artefatos.'],galinha:['Galinha verificando','Crítica, refutação e falso positivo.'],papagaio:['Papagaio comunicando','Clareza, conversa e tradução.'],sherlock:['Sherlock investigando','Fontes, documentos e evidências.'],sara:['Sara avaliando impacto','Relações, cuidado e contexto humano.'],jessica:['Jéssica avaliando risco','Limites técnicos e risco.'],davinci:['Da Vinci organizando','Direção visual e comunicação.']};orbs.forEach(x=>x.addEventListener('click',()=>setState([x.dataset.pet],'selecionando especialista',...info[x.dataset.pet])));$('#boss').addEventListener('click',()=>setState([],'coordenando','Coruja Boss','Coordenação, preflight, integração e controle de qualidade.'));
$$('.filter').forEach(x=>x.addEventListener('click',()=>{$$('.filter').forEach(y=>y.classList.remove('active'));x.classList.add('active');$$('.pet-grid article').forEach(y=>y.classList.toggle('hidden',x.dataset.filter!=='todos'&&y.dataset.cat!==x.dataset.filter))}));
const search=$('#search'),docType=$('#docType');function filterDocs(){const q=(search.value||'').toLowerCase(),type=docType.value;$$('#docs article').forEach(x=>x.classList.toggle('hidden',(q&&!x.innerText.toLowerCase().includes(q))||(type!=='todos'&&x.dataset.type!==type)))}search?.addEventListener('input',filterDocs);docType?.addEventListener('change',filterDocs);
const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),allowed=new Set(['txt','md','json','pdf']),wait=n=>new Promise(r=>setTimeout(r,n)),size=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';
async function hash(file){const h=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function progress(name,n=1){const steps=[['Coruja Boss','Preparando a análise local e definindo o limite desta fase.'],['Macaco','Lendo metadados e calculando SHA-256 no navegador.'],['Galinha','Marcando a saída para conferência humana antes de conclusão.'],['Sherlock','Não acionado: esta fase não consulta fontes externas.']];return '<div class="progress"><div class="progress-head"><div><p class="eyebrow">TRABALHO LOCAL EM ANDAMENTO</p><h2>'+escapeHtml(name)+'</h2></div><span class="badge">SEM UPLOAD</span></div><ol class="steps">'+steps.map((s,i)=>'<li class="'+(i+1<n?'done':i+1===n?'active':'')+'"><span class="mark">'+(i+1<n?'✓':i+1)+'</span><span><b>'+s[0]+'</b><small>'+s[1]+'</small></span></li>').join('')+'</ol></div>'}
function results(file,h,metrics){const ext=(file.name.split('.').pop()||'').toLowerCase(),cards=[['Arquivo',file.name],['Tamanho',size(file.size)],['Tipo',file.type||ext.toUpperCase()||'desconhecido'],...Object.entries(metrics)],note=ext==='pdf'?'PDF: esta Fase 1 mostrou metadados e hash. A extração textual local ainda não foi implementada.':'Processamento concluído inteiramente no navegador.';return '<div class="progress"><div class="progress-head"><div><p class="eyebrow">ANÁLISE ESTRUTURAL LOCAL</p><h2>'+escapeHtml(file.name)+'</h2></div><span class="badge">CONCLUÍDO</span></div><ol class="steps"><li class="done"><span class="mark">✓</span><span><b>Coruja Boss</b><small>Escopo local confirmado.</small></span></li><li class="done"><span class="mark">✓</span><span><b>Macaco</b><small>Metadados e hash calculados.</small></span></li><li class="done"><span class="mark">✓</span><span><b>Galinha</b><small>Saída marcada para conferência humana.</small></span></li></ol><div class="results">'+cards.map(x=>'<div class="result-card"><span>'+escapeHtml(x[0])+'</span><b>'+escapeHtml(x[1])+'</b></div>').join('')+'</div><div class="hash"><b>SHA-256</b><br>'+h+'</div><p class="result-note">'+note+'</p><button class="reset">Limpar resultado</button></div>'}
function show(panel,html){panel.innerHTML=html;panel.querySelector('.reset')?.addEventListener('click',()=>{panel.innerHTML='<div class="empty"><span>⌁</span><b>Resultado limpo</b><small>Escolha outro arquivo quando quiser.</small></div>';apply()})}
async function process(file,panel){if(!file)return;const ext=(file.name.split('.').pop()||'').toLowerCase();if(!allowed.has(ext)){show(panel,'<div class="empty"><span>!</span><b>Formato não suportado</b><small>Escolha TXT, MD, JSON ou PDF.</small></div>');return}setState(['macaco'],'coordenando execução','Coruja iniciou a análise local','Macaco está preparando o arquivo.');show(panel,progress(file.name,1));await wait(180);setState(['macaco'],'processando','Macaco processando','Metadados e SHA-256 são calculados no navegador.');show(panel,progress(file.name,2));try{const h=await hash(file);let m={};if(['txt','md','json'].includes(ext)||file.type.startsWith('text/')){const t=await file.text();m={Caracteres:t.length,Palavras:(t.trim().match(/\S+/g)||[]).length,Linhas:t.split(/\r?\n/).length};if(ext==='json')try{JSON.parse(t);m.JSON='válido'}catch{m.JSON='inválido'}}setState(['macaco','galinha'],'marcando revisão','Resultado estrutural pronto','A saída local foi marcada para conferência humana.');show(panel,progress(file.name,3));await wait(160);show(panel,results(file,h,m));setState(['macaco','galinha'],'resultado pronto','Resultado estrutural pronto','Macaco concluiu; a conferência humana continua necessária.')}catch(e){console.error(e);show(panel,'<div class="empty"><span>!</span><b>Não foi possível processar este arquivo</b><small>Tente novamente com um arquivo válido.</small></div>');setState(['galinha'],'revisando falha','Processamento interrompido','Galinha sinalizou que a saída não pôde ser concluída.')}}
$('#homeFile').addEventListener('change',()=>process($('#homeFile').files?.[0],$('#homeResult')));$('#labFile').addEventListener('change',()=>process($('#labFile').files?.[0],$('#labResult')));const drop=$('#drop');['dragenter','dragover'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(e=>drop.addEventListener(e,x=>{x.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>process(e.dataTransfer.files?.[0],$('#labResult')));$$('[data-scroll-upload]').forEach(x=>x.addEventListener('click',()=>$('#upload').scrollIntoView({behavior:'smooth',block:'center'})));
